### ISSUE TITLE
Spelling correction needed

### ISSUE THREAD

**Issue by chabgood** [toshimaru/rubocop-rails_config#38]
https://github.com/toshimaru/rubocop-rails_config/blob/353850d7354864717ba06abcfbee3c435c0d3656/lib/generators/rubocop_rails_config/update_generator.rb#L15

**Comment by toshimaru** [comment]
What's misspelling??

**Comment by chabgood** [comment]
conifg  - config

**Comment by toshimaru** [comment]
Oh, yes! I've finally found it! 😲
