### ISSUE TITLE
Target Ruby Version 2.5

### ISSUE THREAD

**Issue by toshimaru** [toshimaru/rubocop-rails_config#4]
As of Rails 6, Ruby 2.4 or more is required and rubocop.yml is also configured to use Ruby 2.4.

Ruby2.4 should be used in this project, but I think it’s too early to use Ruby 2.4 because there might be many Ruby 2.3 users.

It’d be good time to update to Ruby 2.4 when Rails 6 is generally available.

**Comment by koic** [comment]
FYI, Rails 6 has been updated to require Ruby 2.5 or higher.
https://github.com/rails/rails/commit/1b7c3222e86b98ce886110ae0860ba62e35e2299

> I think it’s too early to use Ruby 2.4 because there might be many Ruby 2.3 users.

I completely agree. And RubyCop 0.62.0 (latest) still supports Ruby 2.2.

**Comment by nbibler** [comment]
Ruby 2.3 is End Of Life'd as of [2019-03-31](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/):

> Not maintained anymore (EOL):
> Ruby 2.3.8
> sha256: b5016d61440e939045d4e22979e04708ed6c8e1c52e7edb2553cf40b73c59abf

**Comment by SaimonL** [comment]
After updating the gem now I get this error.

`
Error: Unsupported Ruby version 2.2 found in `TargetRubyVersion` parameter (in /Users/test/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rails_config-0.5.1/config/rails.yml). 2.2-compatible analysis was dropped after version 0.69.
Supported versions: 2.3, 2.4, 2.5, 2.6
`

I ran `bundle exec rubocop --config .rubocop.yml`

**Comment by toshimaru** [comment]
Hi, @koic, since Rails 6[ has been released](https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/) officially, I'm wondering if we could drop old Ruby versions - 2,3 and 2.4.

I'd say it's good time to drop. What's your opinion❓

**Comment by koic** [comment]
In fact, Ruby 2.4 is officially supported. Perhaps some rubocop-rails_config users are using Ruby 2.4 and RuboCop also supports Ruby 2.3.

IMHO, maintenance of rubocop-rails_config is not difficult even if it supports Ruby 2.3 and Ruby 2.4.  So I think it would be beneficial for users to support Ruby 2.4 and Ruby 2.3.

I have one implementation idea.

- Leave gemspec `required_ruby_version` specified to `>= 2.3`.
- `TargetRubyVersion` of config/rails.yml is set to `2.5` according to Rails's .rubocop.yml.

However, there is a concern. If rubocop-rails_config specify `2.5` for `TargetRubyVersion`, it will be optimized to Ruby 2.5 or higher. Ruby 2.4 and Ruby 2.3 users means that compatibility may be broken if `TargetRubyVersion` is not changed to `2.3` or `2.4` from `2.5`.

**Comment by toshimaru** [comment]
@koic thanks, I've decided rubocop-rails_config still supports Ruby 2.3+ and updated README about supported Ruby version https://github.com/toshimaru/rubocop-rails_config#targetrubyversion

BTW, Ruby 2.3 is already EOL-ed. so It sounds reasonable to drop Ruby 2.3 and support Ruby 2.4 or more. Do you think we still need to support 2.3?

**Comment by koic** [comment]
Yeah, I don't have a strong intention. Anyway, I think rubocop-rails_config can support Ruby versions that supported by RuboCop. It includes Ruby 2.3. Because maintenance cost of rubocop-rails_config does not increase for the opportunities available to rubocop-rails_config users.

**Comment by toshimaru** [comment]
Indeed, rubocop v0.76.0 still [supports Ruby 2.3](https://rubygems.org/gems/rubocop/versions/0.76.0), so let's keep same supported Ruby version with rubocop. 🚶 

I close this issue, if any concern let me know (or create another issue).
