### ISSUE TITLE
bug in new version rubocop 0.68

### ISSUE THREAD

**Issue by nPaul** [toshimaru/rubocop-rails_config#45]
**$gem install rubocop**

Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.

Put this in your Gemfile.

```rb
gem 'rubocop-performance'
```

And then execute:

```sh
$ bundle install
```

Put this into your .rubocop.yml.

```yaml
require: rubocop-performance
```

More information: https://github.com/rubocop-hq/rubocop-performance
Successfully installed rubocop-0.68.1
Parsing documentation for rubocop-0.68.1
Done installing documentation for rubocop after 4 seconds
1 gem installed

and if RUN rubocop in project folder
$ rubocop
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in /home/pavel/.rvm/gems/ruby-2.6.2/gems/rubocop-rails_config-0.5.1/config/rails.yml, please update it)

**Comment by koic** [comment]
This is a duplicated issue with #42. PR #43 has been opened for solving the issue. The status is below.
https://github.com/toshimaru/rubocop-rails_config/pull/43#issuecomment-490226251
