### ISSUE TITLE
Update README about Rails/RefuteMethods, Rails/AssertNot

### ISSUE THREAD

**Issue by toshimaru** [toshimaru/rubocop-rails_config#55]
`Rails/RefuteMethods`,  `Rails/AssertNot`cop is enabled by default, but to use `asset_not` we need to include `ActiveSupport::Testing::Assertions`. I think it should be explained in README.

ref. https://apidock.com/rails/ActiveSupport/Testing/Assertions/assert_not

## Issue

```
 [Corrected] Rails/RefuteMethods: Prefer assert_not over refute.
    refute ...
```

The code was corrected, but it caused an error because of missing method `assert_not`.

**Comment by koic** [comment]
What is the intention of this issue?

**Comment by toshimaru** [comment]
> What is the intention of this issue?

Oh, sorry for creating an issue without any explanation. I've updated description.
