### ISSUE TITLE
The "Layout/Tab" cop has been renamed to "Layout/IndentationStyle"

### ISSUE THREAD

**Issue by nbibler** [toshimaru/rubocop-rails_config#68]
[Rubocop 0.82.0](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0820-2020-04-16) has renamed `Layout/Tab` to `Layout/IndentationStyle`.

This update results in the following message when running Rubocop:

```
(obsolete configuration found in vendor/bundle/ruby/2.5.0/gems/rubocop-rails_config-0.10.0/config/rails.yml, please update it)
```

**Comment by toshimaru** [comment]
@koic Do you know the current status or rails/rails❓ 

Rails still uses old rubocop version (v0.80), so any plan to update rubocop version in rails/rails?

**Comment by koic** [comment]
Rails bumps RuboCop to 0.82.0 and I opened the PR #69.
https://github.com/koic/rubocop-rails_config/commit/7853e4b0
