### ISSUE TITLE
rubocop-rails_config 1.0

### ISSUE THREAD

**Issue by koic** [toshimaru/rubocop-rails_config#71]
rubocop-rails_config complies with .rubocop.yml in the rails/rails repository, so the APIs is stable for users.
Therefore, I think that rubocop-rails_config can be versioned to 1.0. What do you think about it?

**Comment by toshimaru** [comment]
My original plain is that `rubocop-rails_config` v1.0 will be released after the release of `rubocop` v1.0. 
@koic  What do you think about my plan ❓

**Comment by koic** [comment]
This plan looks good to me. Thank you for planning!
